{
 "title": "Barbeque",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m,2m,5m,10m,20m,30m" },
   {
    "name": "device",
    "label": "Device",
    "query": "SELECT device\nFROM \"bbqmonitor\".\"connection\"\nWHERE time > ago(24h)\nGROUP BY device"
   },
   {
    "name": "alertOn",
    "label": "Probe Alert",
    "query": "SELECT measure_name\nFROM \"bbqmonitor\".\"measurements\"\nWHERE metric = 'temperature'\nAND time > ago(24h)\nGROUP BY measure_name\nORDER by measure_name ASC"
   }
  ]
 },
 "panels": [
  { "title": "Current", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "database": "\"bbq-monitor\"",
     "measure": "temperature1",
     "rawQuery": "WITH latest_recorded_time AS (\n    SELECT\n        measure_name,\n        max(time) as latest_time\n    FROM \"bbqmonitor\".\"measurements\"\n    WHERE metric = 'temperature'\n    AND device = '${device}'\n    AND $__timeFilter\n    GROUP BY measure_name\n)\nSELECT b.measure_name,b.measure_value::bigint, b.time\nFROM latest_recorded_time a\nINNER JOIN \"bbqmonitor\".\"measurements\" b\nON a.measure_name = b.measure_name AND b.time = a.latest_time\nWHERE b.metric = 'temperature'\nAND device = '${device}'\nAND $__timeFilter\nORDER BY b.measure_name",
     "table": "\"temperature\""
    }
   ]
  },
  { "title": "History", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "BBQ Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "database": "\"bbq-monitor\"",
     "measure": "temperature1",
     "rawQuery": "WITH average_readings AS(\nSELECT\n    bin(time, ${interval}) as binned_time,\n    measure_name AS probe,\n    AVG(measure_value::bigint) AS temperature\nFROM \"bbqmonitor\".\"measurements\"\nWHERE metric = 'temperature'\nAND device = '${device}'\nAND $__timeFilter\nGROUP BY measure_name, bin(time, ${interval})\nORDER BY binned_time desc)\n\nSELECT probe, CREATE_TIME_SERIES(binned_time, temperature) as Temperature \nFROM average_readings\nGROUP BY probe",
     "table": "\"temperature\""
    }
   ]
  },
  {
   "title": "Controls",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Damper",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "rawQuery": "WITH average_readings AS(\nSELECT\n    bin(time, ${interval}) as binned_time,\n    measure_name,\n    AVG(measure_value::bigint) AS value\nFROM \"bbqmonitor\".\"device\"\nWHERE (measure_name = 'fanDuty' or measure_name = 'servoOpening')\nAND device = '${device}'\nAND $__timeFilter\nGROUP BY measure_name, bin(time, ${interval})\nORDER BY binned_time desc)\n        \nSELECT measure_name, CREATE_TIME_SERIES(binned_time, value) as Value \nFROM average_readings\nGROUP BY measure_name"
      }
     ]
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temperature",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "celsius" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Battery Percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "rawQuery": "SELECT measure_name, CREATE_TIME_SERIES(time, coalesce(measure_value::bigint, measure_value::double)) as Value \nFROM \"bbqmonitor\".\"device\"\nWHERE (measure_name = 'percentage')\nAND $__timeFilter\nAND device = '${device}'\nAND metric = 'battery'\nGROUP BY measure_name"
      }
     ]
    }
   ]
  },
  {
   "title": "Debug Output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connection Status",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "targets": [
      {
       "database": "\"bbq-monitor\"",
       "measure": "temperature1",
       "rawQuery": "SELECT measure_value::varchar as status, time\nFROM \"bbqmonitor\".\"connection\"\nWHERE $__timeFilter\nAND device = '${device}'\nORDER BY time DESC\nLIMIT 10",
       "table": "\"connection\""
      }
     ]
    },
    {
     "title": "Debug Output",
     "type": "table",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "targets": [
      {
       "database": "\"bbq-monitor\"",
       "measure": "temperature1",
       "rawQuery": "SELECT time as Time, metric as Metric, measure_name as Name, coalesce(measure_value::double, cast(measure_value::boolean as double), cast(measure_value::bigint as double)) as Value\nFROM \"bbqmonitor\".\"device\" \nWHERE $__timeFilter \nAND device = '${device}'\nORDER BY time DESC LIMIT 50",
       "table": "\"connection\""
      }
     ]
    }
   ]
  }
 ]
}